const collectionMapping = {
    TOP_MAC: { iOS: 'topmacapps', Android: 'GROSSING' },
    TOP_FREE_MAC: { iOS: 'topfreemacapps', Android: 'TOP_FREE' },
    TOP_GROSSING_MAC: { iOS: 'topgrossingmacapps', Android: 'GROSSING' },
    TOP_PAID_MAC: { iOS: 'toppaidmacapps', Android: 'TOP_PAID' },

    NEW_IOS: { iOS: 'newapplications', Android: 'GROSSING' },
    NEW_FREE_IOS: { iOS: 'newfreeapplications', Android: 'TOP_FREE' },
    NEW_PAID_IOS: { iOS: 'newpaidapplications', Android: 'TOP_PAID' },

    TOP_FREE_IOS: { iOS: 'topfreeapplications', Android: 'TOP_FREE' },
    TOP_FREE_IPAD: { iOS: 'topfreeipadapplications', Android: 'TOP_FREE' },
    TOP_GROSSING_IOS: { iOS: 'topgrossingapplications', Android: 'GROSSING' },
    TOP_GROSSING_IPAD: { iOS: 'topgrossingipadapplications', Android: 'GROSSING' },
    TOP_PAID_IOS: { iOS: 'toppaidapplications', Android: 'TOP_PAID' },
    TOP_PAID_IPAD: { iOS: 'toppaidipadapplications', Android: 'TOP_PAID' }
};

const categoryMapping = {
    BOOKS: { iOS: 6018, Android: 'BOOKS_AND_REFERENCE' },
    BUSINESS: { iOS: 6000, Android: 'BUSINESS' },
    CATALOGS: { iOS: 6022, Android: 'SHOPPING' },
    EDUCATION: { iOS: 6017, Android: 'EDUCATION' },
    ENTERTAINMENT: { iOS: 6016, Android: 'ENTERTAINMENT' },
    FINANCE: { iOS: 6015, Android: 'FINANCE' },
    FOOD_AND_DRINK: { iOS: 6023, Android: 'FOOD_AND_DRINK' },
    
    GAMES: { iOS: 6014, Android: 'GAME' },
    GAMES_ACTION: { iOS: 7001, Android: 'GAME_ACTION' },
    GAMES_ADVENTURE: { iOS: 7002, Android: 'GAME_ADVENTURE' },
    GAMES_ARCADE: { iOS: 7003, Android: 'GAME_ARCADE' },
    GAMES_BOARD: { iOS: 7004, Android: 'GAME_BOARD' },
    GAMES_CARD: { iOS: 7005, Android: 'GAME_CARD' },
    GAMES_CASINO: { iOS: 7006, Android: 'GAME_CASINO' },
    GAMES_DICE: { iOS: 7007, Android: 'GAME_CASUAL' },
    GAMES_EDUCATIONAL: { iOS: 7008, Android: 'GAME_EDUCATIONAL' },
    GAMES_FAMILY: { iOS: 7009, Android: 'FAMILY' },
    GAMES_MUSIC: { iOS: 7011, Android: 'GAME_MUSIC' },
    GAMES_PUZZLE: { iOS: 7012, Android: 'GAME_PUZZLE' },
    GAMES_RACING: { iOS: 7013, Android: 'GAME_RACING' },
    GAMES_ROLE_PLAYING: { iOS: 7014, Android: 'GAME_ROLE_PLAYING' },
    GAMES_SIMULATION: { iOS: 7015, Android: 'GAME_SIMULATION' },
    GAMES_SPORTS: { iOS: 7016, Android: 'GAME_SPORTS' },
    GAMES_STRATEGY: { iOS: 7017, Android: 'GAME_STRATEGY' },
    GAMES_TRIVIA: { iOS: 7018, Android: 'GAME_TRIVIA' },
    GAMES_WORD: { iOS: 7019, Android: 'GAME_WORD' },
  
    HEALTH_AND_FITNESS: { iOS: 6013, Android: 'HEALTH_AND_FITNESS' },
    LIFESTYLE: { iOS: 6012, Android: 'LIFESTYLE' },
  
    MAGAZINES_AND_NEWSPAPERS: { iOS: 6021, Android: 'NEWS_AND_MAGAZINES' },
    MAGAZINES_ARTS: { iOS: 13007, Android: 'ART_AND_DESIGN' },
    MAGAZINES_AUTOMOTIVE: { iOS: 13006, Android: 'AUTO_AND_VEHICLES' },
    MAGAZINES_WEDDINGS: { iOS: 13008, Android: 'LIFESTYLE' },
    MAGAZINES_BUSINESS: { iOS: 13009, Android: 'BUSINESS' },
    MAGAZINES_CHILDREN: { iOS: 13010, Android: 'FAMILY' },
    MAGAZINES_COMPUTER: { iOS: 13011, Android: 'NEWS_AND_MAGAZINES' },
    MAGAZINES_FOOD: { iOS: 13012, Android: 'FOOD_AND_DRINK' },
    MAGAZINES_CRAFTS: { iOS: 13013, Android: 'HOUSE_AND_HOME' },
    MAGAZINES_ELECTRONICS: { iOS: 13014, Android: 'NEWS_AND_MAGAZINES' },
    MAGAZINES_ENTERTAINMENT: { iOS: 13015, Android: 'ENTERTAINMENT' },
    MAGAZINES_FASHION: { iOS: 13002, Android: 'LIFESTYLE' },
    MAGAZINES_HEALTH: { iOS: 13017, Android: 'HEALTH_AND_FITNESS' },
    MAGAZINES_HISTORY: { iOS: 13018, Android: 'NEWS_AND_MAGAZINES' },
    MAGAZINES_HOME: { iOS: 13003, Android: 'HOUSE_AND_HOME' },
    MAGAZINES_LITERARY: { iOS: 13019, Android: 'BOOKS_AND_REFERENCE' },
    MAGAZINES_MEN: { iOS: 13020, Android: 'LIFESTYLE' },
    MAGAZINES_MOVIES_AND_MUSIC: { iOS: 13021, Android: 'ENTERTAINMENT' },
    MAGAZINES_POLITICS: { iOS: 13001, Android: 'NEWS_AND_MAGAZINES' },
    MAGAZINES_OUTDOORS: { iOS: 13004, Android: 'TRAVEL_AND_LOCAL' },
    MAGAZINES_FAMILY: { iOS: 13023, Android: 'PARENTING' },
    MAGAZINES_PETS: { iOS: 13024, Android: 'LIFESTYLE' },
    MAGAZINES_PROFESSIONAL: { iOS: 13025, Android: 'BUSINESS' },
    MAGAZINES_REGIONAL: { iOS: 13026, Android: 'NEWS_AND_MAGAZINES' },
    MAGAZINES_SCIENCE: { iOS: 13027, Android: 'NEWS_AND_MAGAZINES' },
    MAGAZINES_SPORTS: { iOS: 13005, Android: 'SPORTS' },
    MAGAZINES_TEENS: { iOS: 13028, Android: 'FAMILY' },
    MAGAZINES_TRAVEL: { iOS: 13029, Android: 'TRAVEL_AND_LOCAL' },
    MAGAZINES_WOMEN: { iOS: 13030, Android: 'LIFESTYLE' },
  
    MEDICAL: { iOS: 6020, Android: 'MEDICAL' },
    MUSIC: { iOS: 6011, Android: 'MUSIC_AND_AUDIO' },
    NAVIGATION: { iOS: 6010, Android: 'MAPS_AND_NAVIGATION' },
    NEWS: { iOS: 6009, Android: 'NEWS_AND_MAGAZINES' },
    PHOTO_AND_VIDEO: { iOS: 6008, Android: 'PHOTOGRAPHY' },
    PRODUCTIVITY: { iOS: 6007, Android: 'PRODUCTIVITY' },
    REFERENCE: { iOS: 6006, Android: 'BOOKS_AND_REFERENCE' },
    SHOPPING: { iOS: 6024, Android: 'SHOPPING' },
    SOCIAL_NETWORKING: { iOS: 6005, Android: 'SOCIAL' },
    SPORTS: { iOS: 6004, Android: 'SPORTS' },
    TRAVEL: { iOS: 6003, Android: 'TRAVEL_AND_LOCAL' },
    UTILITIES: { iOS: 6002, Android: 'TOOLS' },
    WEATHER: { iOS: 6001, Android: 'WEATHER' }
  };
    